[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ai-eval-platform"
version = "0.1.0"
dependencies = [
    "pandas",
    "jiwer",
    "presidio-analyzer",
    "presidio-anonymizer",
    "spacy",
    "fastapi[standard]",
    "uvicorn",
    "pyyaml",
    "python-dotenv",
    "requests",
    "google-genai",   # <--- The 2026 SDK
    "google-auth",     # Essential for cloud credentials
    streamlit,
    plotly
]

[tool.setuptools]
packages = ["packages", "packages.eval_core", "packages.eval_runners"]